name: Mobile Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ionic-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ionic-app/**'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ionic-app
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ionic-app/package-lock.json
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build Android APK (Debug)
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ionic-app/android/app/build/outputs/apk/debug/*.apk
        retention-days: 30

  build-ios:
    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: ionic-app
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ionic-app/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Setup iOS environment
      run: |
        # Update CocoaPods
        sudo gem install cocoapods
        
    - name: Sync Capacitor
      run: npx cap sync ios
      
    - name: Install iOS dependencies
      run: |
        cd ios/App
        pod install
        
    - name: Build iOS app
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          archive
          
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ionic-app/ios/App/App.xcarchive
        retention-days: 30